### ISSUE TITLE
do not support hyphenated attribute binding like :auto-play="x"

### ISSUE THREAD

**Issue by Jinjiang** [weexteam/vue-framework-for-Apache-Weex#21]
For example: `:auto-play="x"` will set attribute `auto-play` with value `this.x`.
But actually Weex native DOM accepts camelCased attribute name only (`el.setAttr('autoPlay', this.x)`).
Is there anyway to make `:auto-play` working?

**Comment by yyx990803** [comment]
Since all weex templates are compiled at build time, you can actually just use `:autoPlay="x"`

**Comment by Hanks10100** [comment]
I fixed this by modifying the weex-template-compiler, see [this](https://github.com/vuejs/vue/compare/dev...Hanks10100:patch-compiler). I also fixed the `append="tree"` and add more test case.

I have already publish a new version of following packages (Because there has so many bugs caused by this feature, I have to upgrade it before merge it):

+ [weex-loader](https://www.npmjs.com/package/weex-loader): **^0.4.3**
+ [weex-vue-loader](https://www.npmjs.com/package/weex-vue-loader): **^0.2.10**
+ [weex-template-compiler](https://www.npmjs.com/package/weex-template-compiler): **^2.1.10-weex.1**

**Comment by yyx990803** [comment]
@Hanks10100 can you open the PR so I can merge it upstream?

**Comment by Hanks10100** [comment]
@yyx990803 OK. Sorry for the delay. The ci is failed on my repo, because of the `npm run lint` script. https://circleci.com/gh/Hanks10100/vue/33 

I just send the PR https://github.com/vuejs/vue/pull/4964 . The ci is passed. Maybe is something wrong with my circle ci deploy environment.
